import { FC, JSX } from 'react';
import Head from 'next/head';

interface IMetaProps {
  title: string
}

const Meta: FC<IMetaProps> = ({title}): JSX.Element => {
  return (
    <>
      <Head>
        <title>{title} | RS-School</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};
export default Meta;
